/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1beta1

// GetItems of this ProviderConfigUsageList.
func (p *ProviderConfigUsageList) GetItems() []ProviderConfigUsage {
	return p.Items
}
